### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by howie-cn** [JollyToday/JollyToday-AI_Image_Translator#2]
测试了下贵产品，总体感觉很强大；格式层面基本上可用；
但是对于实际使用来说，是不是可以增加一个翻译人工校正功能，自动翻译的内容有些还是不符合期望
也就是原图片 ->翻译手工矫正(可以默认机器翻译内容 )->目标图片

**Comment by JollyToday** [comment]
Hi，howie
Api和网页版都提供了编辑器，可以编辑文本、形状、底色等内容，新老图片也可以做对比。如下图所示，另外api的接口也支持自己修改文本内容。https://gc100.cdn.izhaoli.cn/ve_material_image/A-a0b03034fcbd457c/225921d95372463790ebe9d782ebbe05/1711977538137.png
